services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Nastya
      - MONGO_INITDB_ROOT_PASSWORD=666246+
  mongo-express:
      image: mongo-express
      container_name: mongo_express
      restart: always
      ports:
       - 8081:8081
      environment:
         - ME_CONFIG_MONGODB_ADMINUSERNAME=Nastya
         - ME_CONFIG_MONGODB_ADMINPASSWORD=666246+
         - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}
